### ISSUE TITLE
Break long strings 

### ISSUE THREAD

**Issue by SirVer** [nrc/rustfmt#108]
One thing that clang-format does that is super useful is to split long strings into shorter ones at whitespace boundaries. In c++ this does not even require a concatenation operator. I am not sure how that works in rust.

It is very useful writing longer text (like error messages or usage help texts) in one string and later run clang-format and it aligns everything nicely. If the text needs editing, clang-format can be rerun and it will merge and split the string again to make it look nice again.

**Comment by marcusklaas** [comment]
If I understand you correctly, then rustfmt already does this in a way. It doesn't break them into shorter strings, but breaks long literals into multiple lines. I just opened a PR with some tests for this functionality: https://github.com/nrc/rustfmt/pull/109.

**Comment by nrc** [comment]
@SirVer do you like the way rustfmt does this? Or do you have ideas to do it better?

**Comment by SirVer** [comment]
No, that is exactly what I had in mind. I wanted to test that feature on a test program:

~~~
struct Error(String);

fn main() {
    let b = Ok(1);
    let e = match b {
        Ok(a) => a,
        Err(e) => Err(Error(format!("Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum: {}", err.description()))),
    };
}
~~~

but unfortunately on my Mac I am unable to run rustfmt at head:

~~~sh
$ rm -rf target
$ cargo build
   Compiling rustfmt v0.0.1 (file:///Users/sirver/Desktop/Programming/rust/rustfmt)
   Compiling rustc-serialize v0.3.14
   Compiling strings v0.0.1 (https://github.com/nrc/strings.rs.git#551331d0)
   Compiling toml v0.1.20
$ target/debug/rustfmt
dyld: Library not loaded: x86_64-apple-darwin/stage2/lib/rustlib/x86_64-apple-darwin/lib/librustc_driver-11582ce5.dylib
  Referenced from: /Users/sirver/Desktop/Programming/rust/rustfmt/target/debug/rustfmt
  Reason: image not found
zsh: trace trap (core dumped)  target/debug/rustfmt
$ rustc --version
rustc 1.2.0-nightly (8937ec100 2015-06-15)
$ git rev-parse HEAD
b74cdb7b533a1c9b37ed66e74ca5246887d9afef
~~~

Should I open a new bug report for that?

**Comment by nrc** [comment]
That looks like some kind of library path error. I've not seen anything like it. I expect it is a local error with your setup. Best path is to ask around on #rust-internals to see if anyone else has seen such an error. If it is a problem with rustfmt, file a bug report, but I suspect it is not.

**Comment by marcusklaas** [comment]
The panic happens because of https://github.com/nrc/rustfmt/issues/86. Rustfmt runs on the same example with a non-tuple struct:
```rust
struct Error {
    x: String,
}

fn main() {
    let b = Ok(1);
    let e = match b {
        Ok(a) => a,
        Err(e) => Err(Error { x: format!("Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum: {}", err.description())}),
    };
}
```
The string literal isn't split correctly, though. I suspect this is because the literal is both inside a macro and a match, neither of which are formatted (yet!)

**Comment by SirVer** [comment]
Without the crash I have the same behavior as you, i.e. the string is not reformatted. My OP also used a string in a format!, so that is why I did not see it fixed. That use case is rather frequent for me though, would be nice to see it fixed.

**Comment by nrc** [comment]
So, I'm pretty sure the only reason this isn't working is because the string is inside a macro. That is a big thing to fix, but possible, and fun. See #35. I think that will completely fix this, so closing this issue.

**Comment by SirVer** [comment]
Makes sense. Thanks.
