### ISSUE TITLE
Indentation of args in function defs

### ISSUE THREAD

**Issue by cassiersg** [nrc/rustfmt#116]
Rustfmt doesn't fix that:
```
fn rewrite_call(context: &RewriteContext,
                     callee: &ast::Expr,
                     args: &[ptr::P<ast::Expr>],
                     width: usize,
                     offset: usize)
                     -> Option<String>
```

**Comment by nrc** [comment]
I hope this is easy, just hunting down the bug, in theory...

**Comment by cassiersg** [comment]
Actually, it seems to be a problem when dealing with a multiple-file crate, it seems that only the main file is fixed for that. I'm investigating...

**Comment by cassiersg** [comment]
Actually, we reformat only the main file in a multiple-file crate. The only test of multiple-file crate was the codebase of rustfmt itself, and it's just an idempotent check...
Closing, see #118.
