### ISSUE TITLE
Format modules in separate files

### ISSUE THREAD

**Issue by cassiersg** [nrc/rustfmt#118]
Currently, nothing is done outside of main file.
Other files are just copied by some `format_missing`. `FmtVisitor::visit_mod` does nothing for these files.

Here is what I think should be done a first sight :
`visit_mod` should be changed to :
- format and add everything until the beginning of the module (may be done with `format_missing`, but it should ideally make some clean rewrite)
- create a new `FmtVisitor` with the right `last_pos` and `block_indent`, call `walk_mod`.
- format missing spans until the end of the module (with the same visitor)

The call to `format_missing` in `fmt_ast` should be removed : all missing spans are handled by `visit_mod`.

**Comment by marcusklaas** [comment]
This looks like a high priority issue to me! Are you working on this, @cassiersg, or could I try my hand at this?

**Comment by cassiersg** [comment]
I have a patch already working, it needs only some cleaning and tests.
