### ISSUE TITLE
Add options for the max number of args/fields on one line

### ISSUE THREAD

**Issue by nrc** [nrc/rustfmt#123]
We currently only move from horizontal to vertical formatting of method decls and calls, and struct literals when we breach the line limit. We should also have an option of having a maximum number for horizontal formatting. E.g., if the max for struct fields is 2, then `Foo { a: 0, b: 1, c: 2 }` would be reformatted as:

```
Foo { a: 0,
      b: 1,
      c: 2,
}
```

**Comment by bluss** [comment]
That style looks odd, doesn't it? The regular linebroken style I would expect looks like this:

```rust
Foo {
    a: 0,
    b: 1,
    c: 2,
}
```
