### ISSUE TITLE
box syntax is reformatted as a borrow

### ISSUE THREAD

**Issue by jdm** [nrc/rustfmt#154]
```rust
fn main() {
  box 5;
}
```
becomes
```rust

fn main() {
    &5;
}
```

**Comment by nrc** [comment]
Whoops!

**Comment by marcusklaas** [comment]
It's not entirely our fault.. Box expression currently aren't represented canonically at the moment: https://github.com/rust-lang/rust/blob/master/src/libsyntax/parse/parser.rs#L2653-L2655
