### ISSUE TITLE
Getting started with this package is unclear. 

### ISSUE THREAD

**Issue by brianllamar** [nrc/rustfmt#168]
I saw your talk today and very interested in using this in my first rust project. I am new to rust as well as cargo and have found the readme for this repo unclear. 

I figured out that I can add the following to my `Cargo.toml`
```
[dependencies.rustfmt]
git = "https://github.com/nrc/rustfmt"
```
But in your presentation you quick ran a command to lint your file (similar to how GOLANG has [fmt](https://golang.org/pkg/fmt/)), what was that? 

Thanks for the presentation and this your work in this repo.

**Comment by marcusklaas** [comment]
Unfortunately I haven't seen @nrc's talk yet, but I may be able to give you some pointers. If you want to format your project's code, you have to compile rustfmt as a binary. To do that, first clone the repository:

`$ git clone https://github.com/nrc/rustfmt.git`

and then run it on the root of your project, usually `src/lib.rs`:

`$ cd rustfmt `
`$ cargo run -- /path/to/your/project/src/lib.rs`

**Comment by brianllamar** [comment]
Thanks @marcusklaas, I attended RustCamp, I believe the talk will be available to watch within a few weeks. 

You explanation was very clear and helpful!
