### ISSUE TITLE
RFC: add `escalation' level to Rewrite

### ISSUE THREAD

**Issue by marcusklaas** [nrc/rustfmt#169]
This is something I've been thinking about while working on https://github.com/nrc/rustfmt/issues/17. A common problem there is that there are generally many ways to split a path over multiple lines.

For example, we format write
```rust
let some_random_var = long::path::With::<'alotof, Parameters, And>::other::stuff(arg1, arg2, arg3, arg4);
```
as 
```rust
let some_random_var = long::path::With::<'alotof, Parameters, And>::other::stuff(arg1,
                                                                                 arg2,
                                                                                 arg3,
                                                                                 arg4);
```
but also as
```rust
let some_random_var = long::path::With::<'alotof,
                                         Parameters,
                                         And>::other::stuff(arg1, arg2, arg3, arg4);
```
or
```rust
let some_random_var = 
    long::path::With::<'alotof, Parameters, And>::other::stuff(arg1, arg2, arg3, arg4);
```

Properly formatting those expressions is one of the core problems of the project. Unfortunately, we are ill-equipped to deal with this. Currently, the deepest expression is the first forced to break the line and only when that is found impossible other options are considered. In the example above, this would always force us in the first case, which may not always be the optimal solution.

To remedy this, I propose to add an - my English lacks a more suitable word - escalation argument to `Rewrite`'s method. The space of escalation parameters could be any well-ordered set. We would assign such an escalation value to every line-breaking operation and only perform those *below* the current escalation level.

Instead of returning `None` on rewrite failure, we should return the minimum observed escalation above the current escalation level to determine what the next escalation level should be.

A pseudo program:
```rust
trait Rewrite {
    const escalation; // do trait constants work like this?

    fn rewrite(&self,
               context: &RewriteContext,
               width: usize,
               offset: usize,
               escalation: Escalation) -> Result<String, Escalation>
    {
        match self.subexpr.rewrite(.., escalation) {
            good@Ok(..) => {
                good
            }
            Err(next_esc) if next_esc <= Self::escalation => {
                self.rewrite(.., next_esc)
            }
            Err(..) if escalation >= Self::escalation => {
                line_breaking_operation();
                try!(self.rewrite(.., Escalation::global_min());
                Ok(format!(...))
            }
            Err(next_esc) => {
                Err(::std::cmp::min(next_esc, Self::escalation))
            }
        }
    }
}
```
This should give us a lot more control over expressions. If we choose our escalation set wisely, we even get to parameterise the behaviour easily (by changing the order).

What do you folks think? Would this adequately solve our problem? Is it too complex? What are the alternatives?

**Comment by nrc** [comment]
Could you give a concrete example of the escalation levels, like how it would work for the assingment example you gave? I can't quite understand the proposal without an example.

It is definitely a problem we need to solve. I had hoped that to some extent we could do without anything so sophisticated - that any given rewrite would do its best to fit the budget, and if it can't then the parent has to come up with more budget. Your example is a good example of where this would give really bad formatting - the path elements *can* format within their budget, but breaking the assignment gives better looking formatting. I'm not sure how to quantify 'better' here, nor how much we should search for better formattings. Does your escalation idea help here?

nb, associated consts basically don't work at all yet.

**Comment by marcusklaas** [comment]
The escalation levels would basically be an ordering of where the line break generally looks best. For example, we could say:

```
binary operator break < assignment break < list break (horizontal listing -> vertical) < parenthesis break < path break
```

I think this approach would force that we try options from left to right, even though they may be higher up in the AST.

**Comment by nrc** [comment]
I wonder if there are circumstances where which kind of break depends on context? E.g., we might prefer list breaking when each item is long, but prefer breaking at an assignment when they're short, e.g.,

```
let this_long_variable_name =
    foo(x, y, z, a, b, c);

// vs

let x = foo_bar_baz_qux(some_long_name,
                        foo.bar.baz.some_method(),
                        another_long_name);
```

Can escalation levels cope with this?

I'm not sure about the heuristic that gives these formattings - something like optimising for the number of non-whitespace chars per line. Perhaps if we can find an heuristic we can actually just search for an optimal formatting. As long as the search space is not too big and we don't have to do it very often, that might work. A lot of 'if's there.

**Comment by marcusklaas** [comment]
Hmmm, nope, I don't think escalation levels can deal with such a situation. That's an important case.

I like the idea of having a search space. Maybe there is a way to construct a tree based on potential line breaks. We could then run arbitrary heuristics on that. For expression that aren't excessively deep we could maybe even do an exhaustive search!

Anyway, it's clear that escalation isn't quite generic enough. Closing this for now. Plenty to think about!
