### ISSUE TITLE
Bad reformatting in imports.rs

### ISSUE THREAD

**Issue by nrc** [nrc/rustfmt#170]
In a call to itemize_list, see https://github.com/cassiersg/rustfmt/commit/e13cc58ac482ddabde98c3919c798ace703190a5#commitcomment-12479359

**Comment by cassiersg** [comment]
This was caused by nrc/strings.rs#3 (bug in `cur_offset`), and fixed in rustfmt by cassiersg/rustfmt@5b5927996f9c78e16d75235d5953d072757c8bae.

**Comment by marcusklaas** [comment]
This seems to be fixed indeed, closing.
