### ISSUE TITLE
Add possibility to remove `*.bk` files

### ISSUE THREAD

**Issue by zummenix** [nrc/rustfmt#171]
While formatting rustfmt generates `*.bk` files. It's very annoying to remove them by separate command. I  think those files are redundant if user uses VCS.

**Comment by nrc** [comment]
Makes sense to have an option that doesn't leave the backups around.

**Comment by marcusklaas** [comment]
Should it be a command line flag or configuration option? It may be tiresome to add the command flag every time.

**Comment by nrc** [comment]
Maybe both? With command line overriding config file.
