### ISSUE TITLE
Reformat match expressions with visual indent

### ISSUE THREAD

**Issue by nrc** [nrc/rustfmt#194]
Rather than block indent. Check other expressions such as `if` to make sure they all do the same thing. We should probably fall back to block indent if we can't do visual indent. (Possibly some heuristic for when visual indent will look bad too).

**Comment by marcusklaas** [comment]
Is this still an issue? We're now doing block indent unless an argument of a multi-line function call, in which case we do a visual indent. It works OK in most cases, I think.
