### ISSUE TITLE
panic on unwrap()

### ISSUE THREAD

**Issue by tschottdorf** [nrc/rustfmt#197]
on `rust{c,fmt}` at time of writing:
```bash
rustfmt <(cat <<EOF
pub struct State<F: FnMut() -> time::Timespec> { now: F }
EOF)
thread '<main>' panicked at 'called `Option::unwrap()` on a `None` value', ../src/libcore/option.rs:364
```

**Comment by marcusklaas** [comment]
Hmm, apparently [ParenthesizeParameterData](http://manishearth.github.io/rust-internals-docs/syntax/ast/struct.ParenthesizedParameterData.html) has an associated span! This is either new or something I missed on my first pass. This should be an easy fix!
