### ISSUE TITLE
--write-mode=true yields "Unrecognized write mode"

### ISSUE THREAD

**Issue by jdm** [nrc/rustfmt#220]
Not really sure what to do about it.

**Comment by jdm** [comment]
I get the same with --write-mode=false, too.

**Comment by marcusklaas** [comment]
The write mode can be "overwrite", "replace" or "display", I believe.

**Comment by jdm** [comment]
Then the message for `-h` should be updated :)

**Comment by marcusklaas** [comment]
Ah yes, was wondering how you got that. At least the README gets it right :p

**Comment by nrc** [comment]
Not the bug is that --help is incorrect

**Comment by cburgdorf** [comment]
I sent a PR for that https://github.com/nrc/rustfmt/pull/252
