### ISSUE TITLE
Can't figure out how to run rustfmt on all of Servo

### ISSUE THREAD

**Issue by jdm** [nrc/rustfmt#222]
"cargo run -- filename to run on a file, if the file includes out of line modules, then we reformat those too. So to run on a whole module or crate, you just need to run on the top file."

When I run on servo/components/servo/lib.rs, it only reformats lib.rs.

**Comment by marcusklaas** [comment]
I believe rustfmt only walks modules, not crates. Not sure if this is intended. @nrc?

**Comment by nrc** [comment]
It should walk the whole crate, but not any dependent crates. The way to walk all the crates is to make Cargo call rustfmt instead of rustc. I've been trying to do this for DXR'ing Servo, but it seems to be buggy.
