### ISSUE TITLE
Rustfmt sometimes formats files which have not been specified

### ISSUE THREAD

**Issue by posix4e** [nrc/rustfmt#233]
It seems as though sometimes i run rustfmt on some files in the repo, rustfmt gets run on the entire repo

github.com/danburkert/procinfo-rs Has this issue. If you run rustfmt on the lib file you get .bk files for every rust file.

**Comment by marcusklaas** [comment]
This is intended behaviour. Rustfmt automatically walks (and formats) all modules defined in your root file, even when they are in different files.

**Comment by jonhoo** [comment]
Would it be reasonable to have a mode in which `rustfmt` does *not* do this, and instead only reformats the given file?

**Comment by Timmmm** [comment]
Yes please can you reopen this? It makes it hard to support `rustfmt` in `arc lint` because when you tell it to format one file it prints a load of other unrelated files.

**Comment by Timmmm** [comment]
Also when using `--emit stdout` the output is completely useless because the filenames are specified *in-band*.

**Comment by Timmmm** [comment]
Aha looking at the source there is [an option for this](https://github.com/rust-lang/rustfmt/blob/master/src/bin/main.rs#L170), sadly it is only available in nightly at the moment. I'll make a PR to stabilise it (it was added 2 years ago!).

**Comment by Timmmm** [comment]
Ok cancel all that. This was fixed [10 days ago](https://github.com/rust-lang/rustfmt/commit/09a028b64d04b720fa55aac0594688bb291297cd) and formatting sub-modules is apparently no longer the default. Yeay!
