### ISSUE TITLE
crash at `>>`

### ISSUE THREAD

**Issue by nrc** [nrc/rustfmt#242]
```
#[derive(Copy, Clone)]
pub struct StdCounter<T: Zero + Add<T, Output = T> + Sub<T, Output = T>> {
    pub value: T
}
```

error is

```
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: IllFormedSpan(Span { lo: BytePos(190), hi: BytePos(189), expn_id: ExpnId(4294967295) })', ../src/libcore/result.rs:734
```

Pretty sure this is due to a libsyntax error (https://github.com/rust-lang/rust/issues/28158), but in case it isn't lets track it here too.

**Comment by ben0x539** [comment]
I get the a similar `IllFormedSpan` error on this snippet, which compiles fine with rustc itself. Does that mean it's not a libsyntax error?

```rust
fn main() {
    match () {_ => () }
}
```

Similarly inserting a space between the `{` and the `_` fixes it.

**Comment by nrc** [comment]
@ben0x539 No, we use more spans than rustc and (more importantly) use them in more interesting ways.

**Comment by nrc** [comment]
And another example (from liballoc):

```
fn homura<T: Deref<Target=i32>>(_: T) { }
```

**Comment by nrc** [comment]
Should be fixed by https://github.com/rust-lang/rust/pull/28291
