### ISSUE TITLE
Add option to always format struct literals as multi-line

### ISSUE THREAD

**Issue by cburgdorf** [nrc/rustfmt#253]
Why does rustfmt reformat this:

```rust
pub fn new(index_arc: Arc<ClassroomIndex>) -> Self {
    Auth {
        index_arc: index_arc,
        workshop_regex: Regex::new("/secure/(.*?)/").unwrap()
    }
}
```

to this:

```rust
pub fn new(index_arc: Arc<ClassroomIndex>) -> Self {
    Auth { index_arc: index_arc, workshop_regex: Regex::new("/secure/(.*?)/").unwrap() }
}
```

Especially since `StructLitStyle::Block` sounds as if it would actually keep the former.

**Comment by nrc** [comment]
Block style means block indenting, as opposed to visual indenting, i.e.,

```
Auth { index_arc: index_arc,
       workshop_regex: Regex::new("/secure/(.*?)/").unwrap() }
```

If a struct literal fits one one line, then that is what we do, if it takes more than one line, then we would use the specified indentation style.

There should probably be an option for forcing multi-line struct lits.

**Comment by nrc** [comment]
There should actually be 3 cases - never do single line structs, only do single line for structs with one field, and always try single line structs. Note that even never should still format unit structs on one line (more of an issue when we allow unit structs with braces).

**Comment by cburgdorf** [comment]
Ah got it.

>There should probably be an option for forcing multi-line struct lits.

:+1:

**Comment by bluss** [comment]
Is it possible to just keep structs multiline if they were multiline?

**Comment by nrc** [comment]
@bluss it could be an option. We're trying to figure out how much we want to use the original source as an input to our heuristics. Not sure where we'll end up on that spectrum. Another possible heuristic option is to force multi-line at some point less than the max width - either for >n items, or for > some width (that is width of the struct lit, not including anything to the left). Again, a bunch of open questions about how best to balance good looking code vs uniformity, etc.

**Comment by trufae** [comment]
Seems that `ForceMulti` doesn't works if `struct_lit_style = "Visual"`. is this expected?

**Comment by nrc** [comment]
@trufae it is not expected, that should work. I expect that would be pretty easy to fix if you wanted to give it a go. Look for `rewrite_struct_lit` in expr.rs.

**Comment by trufae** [comment]
I dont have much time for this right now. If anyone is willing to do the change ill be happy to test.

Thanks
