### ISSUE TITLE
Odd placing of opening brace after reformatting long where clause

### ISSUE THREAD

**Issue by cburgdorf** [nrc/rustfmt#254]
When rustfmt reformats long where clauses it puts the opening brace on a newline.

```rust
pub fn refresh_workshops<'a, T>(workshops: T)
    where T: Iterator<Item = &'a Workshop>
{
```

I would have expected this

```rust
pub fn refresh_workshops<'a, T>(workshops: T)
    where T: Iterator<Item = &'a Workshop> {
```

**Comment by nrc** [comment]
This can be customised with some the option `fn_brace_style`.

**Comment by cburgdorf** [comment]
Sorry, I should have made myself more clear. This happens with `BraceStyle::SameLineWhere`. All functions have their opening brace on the same line as the rest of the signature except that one where it broke down the signature into multiple lines.

**Comment by nrc** [comment]
`SameLineWhere` means that we try to put the brace on the same line unless there is a `where` clause, in which case it goes on a new line. The exception (iirc) is that if the whole function decl fits on one line, then we keep the brace on that line, overriding the `fn_brace_style`. I think that can also be customised with an option. Does that fit your observations?

**Comment by cburgdorf** [comment]
Ah, yes you're right. `PreferSameLine` is what I want :)

**Comment by cburgdorf** [comment]
One follow up question: Why would `PreferSameLine` actually not be an `AlwaysSameLine`? Am I right to assume that it will force it to a new line only when the length of the line is exactly one over the `max_width`?

**Comment by nrc** [comment]
I think that is true and also the reason it is `Prefer` (not 100% sure though).
