### ISSUE TITLE
Explicit closure rewritten without return type

### ISSUE THREAD

**Issue by jdm** [nrc/rustfmt#277]
```diff
-        let reducer = |acc: String, c: &mut &mut Cookie| -> String {
+        let reducer = |acc: String, c: &mut &mut Cookie| {
```

**Comment by marcusklaas** [comment]
How should these be formatted if the arguments + return type don't all fit on a single line? Should the return type jump to the next line or something like
```rust
|arg1,
 arg2,
 arg3| -> RetTy {
    ...
}
```
?

**Comment by jdm** [comment]
My intuition would be that the `-> RetTy {` should jump to the next line.

**Comment by nrc** [comment]
We should probably try to avoid it - e.g., in this case, I would split at the `=` before splitting the closure. If that is not possible, then I'd use the same rules as for functions (with the acknowledgement that any option will look pretty terrible), i.e., 

```
|arg1,
 arg2,
 arg3|
 -> RetTy {
    ...
}
```
