### ISSUE TITLE
Format arithmetic expressions

### ISSUE THREAD

**Issue by nrc** [nrc/rustfmt#29]
Easy-ish, anyway.

**Comment by marcusklaas** [comment]
What are the guidelines for this? Spaces before and after each operator, no spaces around parentheses?

**Comment by nrc** [comment]
@marcusklaas yes. The more interesting thing is where to insert line breaks. If the whole expression fits on the line then great, otherwise we need to insert line breaks. I'm not entirely sure what the optimal heuristics are for that. I expect you want to break at the largest sub-expression which gets us inside the desired width. You may have to keep splitting though. Given that you could know in advance the length of each sub-expression this might be do-able in one pass. Otherwise you might need to kee trying and falling back until you succeed.

The line breaking is why this is easy-ish, not just easy, btw.

Also interesting is how much code we can share with arg listing, etc. Not much, I expect :-(

**Comment by marcusklaas** [comment]
Hmm, that is indeed an interesting problem. That greedy approach will give decent results, I think. It would also be nice to be consistent with operator placement, in the sense of either always placing them at the beginning or always at the end of a line. For example,

```
let x = 400000 + 3000 + 250 +
        33 + 5555555555
        + 7666666;
```

isn't as nice as

```
let x = 400000 + 3000 + 250
        + 33 + 5555555555
        + 7666666;
```

What about (short) functions calls? Are these accepted in arithmetic expressions as well?

**Comment by nrc** [comment]
Yeah, so arithmetic expressions are no separate from the class of expressions as a whole, so you could get any sub-expression as a sub-expression of an arithmetic expression. Also I'm not sure exactly how the parser handles these, you might end up with `(+(+(+ 2 3) 4 ) 5)` rather than `(+ ((+2 3) (+ 4 5))`. You'll need to experiment to find something that ends up looking good.

I'm not sure about where to put the operator on line breaks. Check out the style guide and some more modern parts of the compiler. For boolean expressions we have them trailing. E.g.,

```
foo ||
bar
```

**Comment by marcusklaas** [comment]
This can also be closed.
