### ISSUE TITLE
document config options

### ISSUE THREAD

**Issue by nrc** [nrc/rustfmt#291]
There are a lot of them now, would be good to have docs (preferably generated from config.rs some how).

**Comment by alobb** [comment]
I would be interested in working on this, do you have an idea of how to generate the documentation, or were you thinking rustdoc-style?

**Comment by nrc** [comment]
@alobb great! To be honest, I haven't thought this through very much. We have this `create_config` macro for creating config options, I thought we should add an argument which is basically the documentation string for each option. The macro could then do something like add a `get_docs` method which would return a vec of something (a struct or tuple, etc.) which would have the option name, the doc string, and the set of options it supports (that last is the tricky bit). That would be called by `bin/rustfmt::print_usage` to print out the config options (or maybe there should be a different flag for printing out the config options). Anyway, that is all pretty vague, anything is better than nothing, let me know if you have any questions.

And having written all that, I realise that the easy bit is writing the doc strings. The rest of this is probably a bit harder - if you just want to add doc strings, that would be a great start!

**Comment by alobb** [comment]
Okay, I have it working so that call to print_usage will print out the option names as well as a doc string along with them; any idea how I can use the types in the create_config! macro to find possible options? (Eg., Getting all possible values for a enum from only the enum name).  I looked through the rust book section on macros, but didn't see anything that would help with this.

**Comment by alobb** [comment]
Would it be okay to add https://danielkeep.github.io/rust-custom-derive/doc/enum_derive/index.html as a dependency and use that?

**Comment by nrc** [comment]
@alobb You could use enum_derive, I wouldn't object to the dependency. It wouldn't help make impl_enum_decodable any nicer though, for that you'd need to rewrite it as a syntax extension. If we're keeping impl_enum_decodable, you could probably edit it to add an impl for the enum which has a single static method returning a list of string representations of the enum variants - I think that should be easy enough that you don't need enum_derive, if not, then feel free to use it.

**Comment by alobb** [comment]
@nrc: An update: I found a way to iterate over the enum values by extending impl_enum_decodable, I'm hoping to have a PR ready sometime later tonight.  What should I print out as part of the usage string for possible values for one of the usize parameters? I currently have it as 0-120, but I'm not sure what you want this to be.

**Comment by nrc** [comment]
`<unsigned integer>` is probably the best thing (i.e., just give a type, rather than a range of values).
