### ISSUE TITLE
format array literals

### ISSUE THREAD

**Issue by nrc** [nrc/rustfmt#302]

**Comment by nrc** [comment]
I hesitate to give this an 'easy' label, but I don't think it is super hard.

**Comment by durka** [comment]
Are tuples done already? Seems like this should be very similar to struct literals.

**Comment by marcusklaas** [comment]
Wanted to ask you about this. We could format them with a call to `write_list` using mixed formatting, but then we'll mess up arrays like this: https://github.com/nrc/rustfmt/issues/287..

Any ideas?

**Comment by marcusklaas** [comment]
Tuples have been done already, yes.

**Comment by durka** [comment]
Ok, then I change my answer from "should be similar to structs" to "should be similar to tuples" :)

**Comment by nrc** [comment]
I don't see why write_list would mess up arrays like that, I mean if we reformat where we start the array, we must reformat the array again, but write_list can handle visual indent just fine.

**Comment by marcusklaas** [comment]
I understand, but it won't keep the two items per line. Or should one just use `#[rustfmt_skip]` for such special cases?

**Comment by durka** [comment]
I think splitting the two-items-per-line is a feature.

**Comment by nrc** [comment]
Oh I see what you mean. I don't mind losing the two-per line thing - adding a skip where you really want that (matrices, etc.) is fine. We can't be expected to know about that kind of thing.

However, this would be bad:

```
let x = [0,
         1,
         2,
         3,
         4,
         5,
         6,
         7,
         8,
         9,
         0,
         1,
         2,
         3,
         4,
         5,
         6,
         7,
         8,
         9,
         0];
```

So, we should probably have a feature where if any item is longer than say 10 chars we use `HorizontalVertical`, and if they are all less we use `Mixed` (I hope I have that the right way round).

**Comment by nrc** [comment]
I realise that could happen with tuples too, but I think it is much more likely with array literals.
