### ISSUE TITLE
! return type causes confusion

### ISSUE THREAD

**Issue by nrc** [nrc/rustfmt#320]
e.g.,
```
fn foo() -> ! {}
```

gives `Couldn't make snippet for span Loc { file: FileMap(tests/source/structs.foo), line: 1, col: CharPos(15) }->Loc { file: FileMap(tests/source/structs.foo), line: 1, col: CharPos(14) }`

**Comment by nrc** [comment]
There seems to be some bad spans here - both the surrounding module and the name of the function seem to have incorrect spans.

**Comment by nrc** [comment]
FIxed

**Comment by marcusklaas** [comment]
We should probably have a regression test for this at some point.
