### ISSUE TITLE
empty match arms should not be multi-line

### ISSUE THREAD

**Issue by nrc** [nrc/rustfmt#339]
I thought this worked as such, but apparently not:

```
None => { }
```
expected:
```
None => {}
```

actual:
```
None => {
}
```

**Comment by scyptnex** [comment]
```
None => {

}
```
i.e. with an empty newline

expected:
```
None => {}
```
 as well?

**Comment by nrc** [comment]
Yes.

However if there's a comment in there, it should be preserved:

```
None => {
    // A comment.
}
```

**Comment by nrc** [comment]
Note that locks (irc nick, don't know GH username) has also been looking at this issue.

**Comment by locks** [comment]
Seems like @scyptnex got to it! I shall move to one of the other ones.
