### ISSUE TITLE
Arithmetic overflow in string::rewrite_string (string.rs, line 61)

### ISSUE THREAD

**Issue by llogiq** [nrc/rustfmt#343]
Apparently, on formatting current [rust-clippy](https://github.com/Manishearth/rust-clippy/tree/cf4e48d148812e4d84b93e5149e1a3a928f3d637), it so happens that `cur_end == 0`, which makes the code panic because `cur_end - 1` wraps around.

Checking against zero by changing line 61 to

       while cur_end > 0 && !(graphemes[cur_end - 1].trim().len() == 0) {

just leads to a `panic at 'position 4954 does not resolve to a source location', ../src/libsyntax/codemap.rs:976`, so there is a more subtle issue below.

**Comment by marcusklaas** [comment]
That last panic seems to be a macro invocation which we fail to parse. It shouldn't propagate to the main thread.

-----Original Message-----
