### ISSUE TITLE
Can't build on a Mac

### ISSUE THREAD

**Issue by sezna** [nrc/rustfmt#348]
I have the latest nightly build of Rust and I'm on a Macbook Pro 2014, not sure if that matters but this issue seems like it might.

When I cargo build it, I get the following errors:

    src/macros.rs:52:9: 52:55 error: no associated item named `MacInvocTT` found for type `syntax::ast::Mac_` in the current scope
    src/macros.rs:52     let ast::Mac_::MacInvocTT(ref path, ref tt_vec, _) = mac.node;
                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    src/macros.rs:58:15: 58:32 error: the type of this value must be known in this context
    src/macros.rs:58     } else if tt_vec.is_empty() {
                                   ^~~~~~~~~~~~~~~~~
    src/macros.rs:56:5: 64:6 note: in this expansion of if let expansion
    error: aborting due to 2 previous errors
    Could not compile `rustfmt`.

Thanks!

**Comment by kecolus** [comment]
It appears that the follow update to the Rust compiler caused this problem: 

https://github.com/rust-lang/rust/commit/85b8b447fa3c6fc4aa2e7d957ac15357d0cb3861

By the way, I am running Debian and see the same errors.

**Comment by sezna** [comment]
I'm not sure how to fix that, it seems to be on a lower level than I'm familiar with. Should I just downgrade rust and try again?

**Comment by kecolus** [comment]
I would wait until someone fixes rustfmt. It looks like it won't be too difficult to fix.

**Comment by kecolus** [comment]
And the fix has been coded. It just needs to be merged. 

https://github.com/nrc/rustfmt/pull/349

**Comment by nrc** [comment]
Fixed by #349
