### ISSUE TITLE
Show rustfmt coverage

### ISSUE THREAD

**Issue by nrc** [nrc/rustfmt#351]
It would be nice to see where we format and where we skip formatting. I think we can do this fairly easily when we format a missing span, rather than just pasting out the snippet for the span, we replace all non-whitespace chars with `X`s or emoji sad faces or something.

As a bonus, it would be great if we could (optionally) report how much of a format was skips. So after a test or run on a module, we could report - "75% of this module was rewritten". The goal would be for tests to assert we always hit 100%.

**Comment by nrc** [comment]
And if we could distinguish between skipping due to [#rustfmt_skip] and skipping due to us not being able to format, that would be awesome.

**Comment by Wafflespeanut** [comment]
I'll take this :)

**Comment by nrc** [comment]
@Wafflespeanut great! Let me know if you want any pointers for things to at, or if you get stuck with anything

**Comment by Wafflespeanut** [comment]
@nrc At first I'd thought this wouldn't need AST, because my idea was to compare the contents of the original file with the [formatted output](https://github.com/nrc/rustfmt/blob/master/src/filemap.rs#L49) we obtain here, but that won't work (because we can't know whether stuff has been moved to new lines), and it's also inefficient :/

So, we need to add something to track the changes made to each span of line. Can you give me a head start, like where exactly do I begin? :)

**Comment by nrc** [comment]
@Wafflespeanut So, the way rustfmt works is that it looks at each AST item and tries to rewrite it. Anything since the end of the last ast item and the start of the current would be missed, so we just paste that into the new output verbatim without reformatting. If we can't rewrite an AST item then we just forget about it - since we don't update our position in the file, then when we get the next item the skipped item will be included in the missed code which is copied verbatim.

What I want to know with this work is, looking at the output from rustfmt, how much is rewritten and how much was copied verbatim because it was missed?

In particular, I don't care if the original and the formatted version are identical, as long as rustfmt has actually processed the code.

The strategy I had in mind for tackling this was that when we paste the missed code into the output we do a simple text substitution, replacing any non-whitespace character with `X`(or whatever). E.g,

```
ast::ItemExternCrate(ref s) => {
    let location = match *s {
        Some(s) => s.to_string(),
        None => item.ident.to_string(),
    };
}
```

would become

```
XXXXXXXXXXXXXXXXXXXXXXXX XX XX X
    XXX XXXXXXXX X XXXXX XX X
        XXXXXXX XX XXXXXXXXXXXXXX
        XXXX XX XXXXXXXXXXXXXXXXXXXXXXX
    XX
X
```

although, actually, it might be better to replace spaces too, but preserve newlines:

```
XXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXX
X
```

To see where and how we take care of missed code, take a look at https://github.com/nrc/rustfmt/blob/master/src/missed_spans.rs.

You'll want to add a new WriteMode - `DisplayCoverage` or something, see https://github.com/nrc/rustfmt/blob/master/src/lib.rs#L167-L179 for the enum.

Outputting the coverage like this would be a good start, once that works, lets land a PR and then do percentages, etc. as a follow-up.

**Comment by Wafflespeanut** [comment]
@nrc It seems to me that the `missed_spans` only takes care of the non-AST stuff like comments, and the formatting is done along the way line by line (if I get it right). Even then, I'm confused, because the methods take a mutable reference and update the `StringBuffer` directly. If I do as you've said, wouldn't all the formatted output be actually `X` which would destroy rustfmt?

**Comment by nrc** [comment]
I think if you modify `write_snippet` so that it checks the display mode, and if we're in the coverage mode, then it processes `snippet` (doing the find and replace), then passes the modified snippet to `push_str` and `process_last_snippet`, then we will get the desired effect - i.e., only modifying the output data.

I'm not sure about code that has been missed, I think that is handled here too. But I would start here and see what happens - if it's only the comments, then at least that works which proves the concept and we can work on the rest.
