### ISSUE TITLE
Insert semi-colons after return, continue, and break

### ISSUE THREAD

**Issue by nrc** [nrc/rustfmt#353]

**Comment by steveklabnik** [comment]
:+1:

**Comment by nrc** [comment]
Ideally, we would do this in all places where an expression is used as a value and has void type, but we don't yet have type information in rustfmt, so can't do that. And sometimes people do this intentionally. Doing it just for void keywords seems easier and safer.

**Comment by retep998** [comment]
As long as there is an option for this.

**Comment by nagisa** [comment]
I personally prefer not to, since they add no value whatsoever and are generally just a waste of bytes 😉

**Comment by Ms2ger** [comment]
Strongly agree.

**Comment by nrc** [comment]
@Ms2ger with which opinion?

**Comment by Ms2ger** [comment]
With the title of this issue: add them.
