### ISSUE TITLE
Put the closing brace of an empty function on the same line

### ISSUE THREAD

**Issue by chris-morgan** [nrc/rustfmt#36]
```rust
fn _assert_send<T: Send>() { }  // Not uncommon in library testing
fn main() { }  // Common in trivial “does this technique work?” experiments
```

In cases like these I would tend to prefer the closing curly brace on the same line rather than on the next line as rustfmt currently does.

Opinions may differ here.

**Comment by nrc** [comment]
I think I agree, the existing situation is more by chance than by design.

**Comment by nrc** [comment]
There is also the situation where the body of the function is a single expression and the whole function
can fit on one line. Some people want this to then stay on one line (I disagree, but I think it warrants an option).

**Comment by chris-morgan** [comment]
Yeah, I don’t like putting a single expression body of a function on the same line either, as a generalisation at least.

**Comment by nrc** [comment]
Subsumed by #262
