### ISSUE TITLE
panic from unwrap in format_struct

### ISSUE THREAD

**Issue by killercup** [nrc/rustfmt#360]
I'm trying to format [this file here](https://github.com/killercup/vibrant-rs/blob/1d58699e921129b07bcbf04f3d2a4069953b81cb/src/palette.rs) with rustfmt (`e80080deb6`), but it fails with this backtrace:

```plain
$ env RUST_BACKTRACE=1 rustfmt src/palette.rs
thread '<main>' panicked at 'called `Option::unwrap()` on a `None` value', ../src/libcore/option.rs:365
stack backtrace:
   1:        0x10a035ec0 - sys::backtrace::tracing::imp::write::h7dbd2530c1047b579at
   2:        0x10a0336a3 - panicking::on_panic::h3eaf6afa91cfdda4HZw
   3:        0x109ffe0c2 - sys_common::unwind::begin_unwind_inner::h1a718137b639f1bbjas
   4:        0x109ffeb6e - sys_common::unwind::begin_unwind_fmt::h6bdd95feebed4c54p9r
   5:        0x10a032f27 - rust_begin_unwind
   6:        0x10a07c710 - panicking::panic_fmt::h3b414ef7ca9e7ec0wZK
   7:        0x10a0768bc - panicking::panic::h9b421e50eb8c225f3XK
   8:        0x105f0ce73 - items::FmtVisitor<'a>::format_struct::h42d7ceadec7815c3m6c
   9:        0x105efa6ad - visitor::FmtVisitor<'a>.visit..Visitor<'v>::visit_item::h31a2fc7fab4adfbbz7b
  10:        0x105f49a5f - RustFmtCalls.CompilerCalls<'a>::build_controller::closure.26813
  11:        0x10601e7eb - driver::compile_input::hc113799f837834bc0ba
  12:        0x1061832b0 - run_compiler::hab6cd61a349ae7d43qc
  13:        0x105f4b6e0 - format::hedcf54d01cda8efdPOi
  14:        0x105f4c112 - run::h065ec11ccd147b85EPi
  15:        0x105ec91fa - main::hbe05312b2180e0250da
  16:        0x10a03b872 - sys_common::unwind::try::try_fn::h10603582835175917823
  17:        0x10a032d68 - __rust_try
  18:        0x10a03b718 - rt::lang_start::h1a3aeee2120b0980sXw
```

Looks like [this line](https://github.com/nrc/rustfmt/blob/e80080deb60e78e7a57be4d693ca8e96cb14a1b2/src/items.rs#L791) in `items::FmtVisitor<'a>::format_struct` is the only one directly calling `.unwrap()`. I can't see where [`write_list`](https://github.com/nrc/rustfmt/blob/e80080deb60e78e7a57be4d693ca8e96cb14a1b2/src/lists.rs#L102) returns `None`, though.

I can try to recompile rustfmt in debug mode and investigate further.

- - -

```plain
$ rustc -vV
rustc 1.5.0-nightly (b2f379cdc 2015-09-23)
binary: rustc
commit-hash: b2f379cdc23aec5c5d0d62acfcc5a4a18ebf0e30
commit-date: 2015-09-23
host: x86_64-apple-darwin
release: 1.5.0-nightly
```

**Comment by nrc** [comment]
Confirmed the crash and the crashing line is the one suggested (items.rs:791).

**Comment by nrc** [comment]
Minimal test case:
```
struct Palette {
    /// A map of indizes in the palette to a count of pixels in approximately that color
    foo: i32,
}
```

This is weird - It seems to be due to the length of the doc comment - changing to a normal comment fixes it and reducing the length of the doc-comment fixes it - 83 chars is OK, 84 crashes (including the `///`, but not the indent). Note that doc comments are treated as attributes, which explains the comment vs doc comment thing, why the length is important, I've no idea.

**Comment by killercup** [comment]
`wrap_str` returns `None` [here](https://github.com/nrc/rustfmt/blob/e80080deb60e78e7a57be4d693ca8e96cb14a1b2/src/lists.rs#L218).

**Comment by marcusklaas** [comment]
This should be an easy fix, then.
