### ISSUE TITLE
Request to format inverted span

### ISSUE THREAD

**Issue by sfackler** [nrc/rustfmt#38]
I'm running into a panic trying to format a branch of rust-postgres:

```
thread '<main>' panicked at 'Request to format inverted span: Loc { file: FileMap(../rust-postgres/src/lib.rs), line: 268, col: CharPos(34) } to Loc { file: FileMap(../rust-postgres/src/lib.rs), line: 263, col: CharPos(4) }', src/missed_spans.rs:52
```

It corresponds to this comment block: https://github.com/sfackler/rust-postgres/blob/12479c1f0c5c48eb3fb0b47fae60d69e6b8f38d3/src/lib.rs#L263-L268

**Comment by marcusklaas** [comment]
I cannot reproduce this. Maybe it has been resolved?
