### ISSUE TITLE
Inverted span when function contains doc comment

### ISSUE THREAD

**Issue by marcusklaas** [nrc/rustfmt#382]
```rust
fn main() {
    //! Translates `base[idx]`.
}
```
output:
thread `<main>` panicked at 'Request to format inverted span: Loc { file: FileMap(../rust/src/librustc_trans/trans/expr.rs), line: 786, col: CharPos(31) } to Loc { file: FileMap(../rust/src/librustc_trans/trans/expr.rs), line: 780, col: CharPos(0) }', src/missed_spans.rs:54

Possibly related to https://github.com/nrc/rustfmt/issues/364.

**Comment by marcusklaas** [comment]
Another test case:
```rust
fn main() {
        /*!
         * Attempts to coerce from the type of a Rust function item
         * into a closure or a `proc`.
         */
}
```

**Comment by nrc** [comment]
(I've been avoiding making bugs (as opposed to poor formatting) p-high, but I'm hitting this *a lot*).

**Comment by marcusklaas** [comment]
Fixed by https://github.com/nrc/rustfmt/pull/423.
