### ISSUE TITLE
When splitting strings without spaces, look for punctuation

### ISSUE THREAD

**Issue by nrc** [nrc/rustfmt#389]
```
-        format!("file_name,\"{}\",file_line,{},file_col,{},extent_start,{},extent_start_bytes,{},\
-                 file_line_end,{},file_col_end,{},extent_end,{},extent_end_bytes,{}",
+        format!("file_name,\"{}\",file_line,{},file_col,{},extent_start,{},extent_start_bytes,{},f\
+                 ile_line_end,{},file_col_end,{},extent_end,{},extent_end_bytes,{}",
```

We should prefer splitting at `,` `.` `;` `:` rather than the middle of a word.

**Comment by nagisa** [comment]
http://www.unicode.org/reports/tr14/

**Comment by sezna** [comment]
I'm figuring out how to fix this (it seems easy and I am looking to start helping), but I can't seem to test it. When i try to format a very long string, rustfmt won't even let me format lines that are that long.

**Comment by nrc** [comment]
Could you give an example of input and the error message? That is unexpected and sounds like a bug.

**Comment by sezna** [comment]
Nevermind, sorry, it was my bad. I'm can now test my code.
