### ISSUE TITLE
If FILE.rs.bk exists, rustfmt will sometimes overwrite it with formatted FILE.rs, regardless of write-mode

### ISSUE THREAD

**Issue by aarzee** [nrc/rustfmt#399]
```
carloss-mbp:rustfmt aarzee$ touch /Users/aarzee/coreutils/src/common/c_types.rs.bk
carloss-mbp:rustfmt aarzee$ stat /Users/aarzee/coreutils/src/common/c_types.rs.bk
16777220 3360231 -rw-r--r-- 1 aarzee staff 0 0 "Sep 29 13:38:51 2015" "Sep 29 13:38:51 2015" "Sep 29 13:38:51 2015" "Sep 29 13:38:51 2015" 4096 0 0 /Users/aarzee/coreutils/src/common/c_types.rs.bk
carloss-mbp:rustfmt aarzee$ cargo run --release -- /Users/aarzee/coreutils/src/common/c_types.rs 
     Running `target/release/rustfmt /Users/aarzee/coreutils/src/common/c_types.rs`

carloss-mbp:rustfmt aarzee$ stat /Users/aarzee/coreutils/src/common/c_types.rs.bk
16777220 3360138 -rw-r--r-- 1 aarzee staff 0 7232 "Sep 29 13:39:14 2015" "Sep 29 13:36:57 2015" "Sep 29 13:36:57 2015" "Sep 29 13:36:57 2015" 4096 16 0 /Users/aarzee/coreutils/src/common/c_types.rs.bk
```
[`c_types.rs`](https://github.com/uutils/coreutils/blob/master/src/common/c_types.rs) causes this issue. Notice the change in file size and modification date.

**Comment by marcusklaas** [comment]
Hmmm, I can't reproduce this. Could you post some extra context?

**Comment by aarzee** [comment]
I just updated the issue with more details, could you try again?

**Comment by marcusklaas** [comment]
Ah, thanks. Will play around with it a bit.

**Comment by marcusklaas** [comment]
I am hitting this now. This is most curious. Thanks for the report!

**Comment by marcusklaas** [comment]
Wait, doesn't it make sense?

**Comment by marcusklaas** [comment]
When you run rustfmt in replace mode twice, it will overwrite the backup file with the output of the first run.

**Comment by marcusklaas** [comment]
Not sure if this should be the behaviour.. maybe we should simply overwrite if the backup file is found, or abort?

**Comment by aarzee** [comment]
You might be right. I only came into the issue by running a Python script to run it on all .rs files in a directory (recursively)... I may be running it on the same file more than once. I'm going to double check that everything in this script is working correctly.

**Comment by marcusklaas** [comment]
Note that `rustfmt` automatically is run on all child modules, even when those are in separate files. For most libraries, running rustfmt on `src/lib.rs` is enough to format all your code!

**Comment by aarzee** [comment]
That would be the issue. Sorry for the confusion! Closing. On another note, however, is there a way to disable that? (I'm running it on a complicated project which consists of many crates with some common files).

**Comment by marcusklaas** [comment]
Not as of this moment, no. But wait, crates having common files? That's madness, yo!

**Comment by aarzee** [comment]
They're in fact not primarily crates. While building them with Cargo is an option, the normal method is using a Makefile. (The project is [uutils/coreutils](https://github.com/uutils/coreutils)). Should I open an issue for having that as an option?

**Comment by marcusklaas** [comment]
Sure, that sounds good. I'm curious to see what others think about that.
