### ISSUE TITLE
Document 'position <X> does not resolve to a source location' errors in README

### ISSUE THREAD

**Issue by ihrwein** [nrc/rustfmt#414]
@marcusklaas said:
> It'll be hard to improve the error message since it's emitted by libsyntax and we can't change it. We could definitely make it clearer in the README what are causing those panics though.

The errors are caused by macro invocations with trailing commas:

```Rust
vec![
    msg_id1.clone(),
    msg_id2.clone(),
    msg_id3.clone(),
]
```

This issue is about documenting this behavior in the README file.

# Original issue

I've got a bunch of these kinds of errors without indicating their failing place.

You can reproduce it easily by running `rustfmt` on the `dev` branch of this repo:

https://github.com/ihrwein/correlation/

## Stacktrace
```
thread '<main>' panicked at 'position 51889 does not resolve to a source location', ../src/libsyntax/codemap.rs:980
thread '<main>' panicked at 'position 4711 does not resolve to a source location', ../src/libsyntax/codemap.rs:980
thread '<main>' panicked at 'position 5630 does not resolve to a source location', ../src/libsyntax/codemap.rs:980
thread '<main>' panicked at 'position 7462 does not resolve to a source location', ../src/libsyntax/codemap.rs:980
thread '<main>' panicked at 'position 8804 does not resolve to a source location', ../src/libsyntax/codemap.rs:980
thread '<main>' panicked at 'position 63287 does not resolve to a source location', ../src/libsyntax/codemap.rs:980
thread '<main>' panicked at 'position 41664 does not resolve to a source location', ../src/libsyntax/codemap.rs:980
thread '<main>' panicked at 'position 42742 does not resolve to a source location', ../src/libsyntax/codemap.rs:980
thread '<main>' panicked at 'position 43796 does not resolve to a source location', ../src/libsyntax/codemap.rs:980
thread '<main>' panicked at 'position 44955 does not resolve to a source location', ../src/libsyntax/codemap.rs:980
```

**Comment by marcusklaas** [comment]
I haven't looked deeper into this, but panicking this many times in a single run typically just means that rustfmt encounter macro invocations which aren't list-like.

**Comment by ihrwein** [comment]
I used `vec!{}` in two places. If I remove those I still get the errors.

**Comment by marcusklaas** [comment]
I've run rustfmt on your library and I'm seeing the same panics, but it finishes okay. We currently fail parsing macro invocations with trailing comma's such as:

```rust
vec![
    msg_id1.clone(),
    msg_id2.clone(),
    msg_id3.clone(),
]
```

**Comment by ihrwein** [comment]
Ah thanks :)

Should I rename the issue to something else? like mentioning not panicking or improving error message, etc.

**Comment by marcusklaas** [comment]
That sounds like a good idea.

It'll be hard to improve the error message since it's emitted by libsyntax and we can't change it. We could definitely make it clearer in the README what are causing those panics though.

**Comment by ihrwein** [comment]
If you don't mind I'll update the bug description with your comment. If people come here via a search engine they don't have to read all the comments.

**Comment by marcusklaas** [comment]
:+1:

**Comment by ihrwein** [comment]
done, thanks!

**Comment by nrc** [comment]
Why do we fail parsing the macro when rustc doesn't? That seems like something we ought to be able to fix (at least to avoid the panic, if not actually format the thing).

**Comment by marcusklaas** [comment]
If we'd format it, we wouldn't restore the trailing comma and risk changing the semantics, right? Preventing a panic is surely possible, at least.

**Comment by nrc** [comment]
Yeah, I'm not so bothered about reformatting, but it would be nice to not panic.
