### ISSUE TITLE
erroneous trailing comma on single line struct

### ISSUE THREAD

**Issue by nrc** [nrc/rustfmt#421]
```
-        dirs.push(LogDirective {
-            name: name.map(str::to_owned),
-            level: log_level,
-        });
+            dirs.push(LogDirective { name: name.map(str::to_owned), level: log_level, });
```

Shouldn't be a comma after log_level.

I think this should also be formatted multi-line, I thought we tried to do that for all struct lits with >1 field.

**Comment by marcusklaas** [comment]
This is super weird. I'll look into it.

**Comment by marcusklaas** [comment]
I can't reproduce this. I'm fairly certain this has been fixed a while back.

Are you using the most recent version of rustfmt master, @goyox86?

**Comment by nrc** [comment]
It may have been a manual fixup, it wasn't clear what was rustfmt and what was manual. Closing for now.
