### ISSUE TITLE
Floating method call inside function arguments

### ISSUE THREAD

**Issue by gkoz** [nrc/rustfmt#426]
https://github.com/rust-lang/rust/pull/28907/files?diff=split#diff-ab0d9958e47d3ad564f76ab645164778L303
```diff
             PushParam => {
                 // params are 1-indexed
                 // params are 1-indexed
                 stack.push(mparams[match cur.to_digit(10) {
                 stack.push(mparams[match cur.to_digit(10) {
                     Some(d) => d as usize - 1,
                     Some(d) => d as usize - 1,
-                    None => return Err("bad param number".to_owned())
+                    None => return Err("bad param number".to_owned()),
-                }].clone());
+                }]
-            },
+                               .clone());
+            }
```

**Comment by marcusklaas** [comment]
This is a tough issue. We place multi-line method calls on the next line with an extra level of indentation. This generally produces fairly readable results, but when the previous expression ends with a line that is nearly blank we get those floating parts...

Not sure how we could best solve this. I'm not a fan of simply appending it to the child expression, as it's not really consistent and doesn't generalize well to long chains of method calls.

**Comment by nrc** [comment]
If this were my code I would use a local variable here, I find the compound statement very awkward to read, which means I don't care too much if rustfmt screws it up. OTOH, this is *really* weird looking. I wonder if there is some heuristic about appending the child if there is enough space and the child is 'orphaned' by being under whitespace?
