### ISSUE TITLE
What are the style guideline you are using

### ISSUE THREAD

**Issue by gbersac** [nrc/rustfmt#436]
Could you provide a link to the style guideline you took as reference ? Searching on google give many answer, I don't know which one to choose.

This is this one ? 
https://aturon.github.io/README.html

**Comment by killercup** [comment]
The current style guide lives in [rust/src/doc/style](https://github.com/rust-lang/rust/tree/master/src/doc/style) and can be seen here: http://doc.rust-lang.org/nightly/style/

It's still pretty incomplete, though. See the discussion here: https://www.reddit.com/r/rust/comments/3nt2vm/rustfmting_rust_please_help_me_rustfmt_the_rust/cvrc072

**Comment by nrc** [comment]
Yeah, http://doc.rust-lang.org/nightly/style/ is probably the best link, it's where I started from, I basically tried to copy the style we use in the compiler and allow lots of customisation. The reddit comments have more detail.
