### ISSUE TITLE
Inline `if .. else` expression

### ISSUE THREAD

**Issue by barosl** [nrc/rustfmt#452]
`if .. else` is sometimes used in lieu of the ternary operator in C, so it might be a good idea to preserve the original intention if the programmer wrote a short `if .. else` expression in a single line.

A wild case found in rust-lang/rust#28988:

```rust
if align <= MIN_ALIGN { 0 } else { mallocx_align(align) }
```

was converted into:

```rust
if align <= MIN_ALIGN {
    0
} else {
    mallocx_align(align)
}
```

which looks a bit more verbose. Is this an intended behavior?

Hmm, well, looking at the code again, the latter also seems OK to me... Now I'm not sure which side I'm in. Maybe this should be exposed as a configuration option?

**Comment by nrc** [comment]
It is intended, but it's a style that's often requested, so we should probably have an option for it.

(I thought there was an issue for this already, but I couldn't find one).

**Comment by mseri** [comment]
+1 on this. There are some libraries in rust-lang in which this change is made all-over the place, even for very short lines.

**Comment by marcusklaas** [comment]
This is already possible by setting `single_line_if_else` to true in the config!

**Comment by marcusklaas** [comment]
https://github.com/nrc/rustfmt/blob/master/tests/target/single-line-if-else.rs has some example output.

**Comment by nrc** [comment]
Ha! That is why I couldn't find an issue :-)

**Comment by mseri** [comment]
Ah cool! Thanks!!

**Comment by wfxr** [comment]
@marcusklaas Was option `single_line_if_else` removed?

```bash
$ rustfmt --version
rustfmt 1.4.11-nightly (1838235 2019-12-03)
$ rustfmt main.rs
Warning: Unknown configuration option `single_line_if_else`
```

**Comment by marcusklaas** [comment]
I do not know. I haven't been involved with this project for a long time.

**Comment by Enigmartyr** [comment]
even with `single_line_if_else` if the if-else statement is your return value then the formatter will still open the statement up unless you explicitly use the return keyword (which I believe isn't idiomatic, ironically)
