### ISSUE TITLE
Bad indentation in nested let.

### ISSUE THREAD

**Issue by nrc** [nrc/rustfmt#492]
```
+                let consequent_match_pairs = subpatterns.into_iter()
+                                                        .map(|subpattern| {
+                                                            let lvalue =
                                        downcast_lvalue.clone().field(
```

We seem to reformat the expression properly, but the nested statement keeps its original indent.

**Comment by marcusklaas** [comment]
This is a dupe of https://github.com/nrc/rustfmt/issues/470.

**Comment by nrc** [comment]
They look different to me - I guess this could be a sub-case of #470. Leaving open for now, although I bet they get closed together.

**Comment by marcusklaas** [comment]
It's a rewrite of `ast::Block` that runs out of space and simply takes the original span.
