### ISSUE TITLE
When a `//!` comment is too long, turns it into a `// !`

### ISSUE THREAD

**Issue by steveklabnik** [nrc/rustfmt#524]
https://github.com/brianloveswords/hookshot/pull/22/files#r42826103

**Comment by marcusklaas** [comment]
This should have been fixed a few days ago. There's some other dated behaviour in that PR as well. Was the latest master version used?

**Comment by brianloveswords** [comment]
Confirmed that this is not happening with `rustfmt`@https://github.com/nrc/rustfmt/commit/7e76fad1f55945c196b32e6629ebaecc4ebfda74

**Comment by steveklabnik** [comment]
I _thought_ I had done a fresh pull, but

```
commit: 526ccff690bee0adf7f93ece0d2bba16db42413d
Date:   Mon Oct 19 23:09:04 2015 +0200
```

Thanks!
