### ISSUE TITLE
Build problem

### ISSUE THREAD

**Issue by minsler** [nrc/rustfmt#88]
Hi. I have a problem with a building of the project 
<pre>
dm-mbp:rustfmt minsler$ rustc -V
rustc 1.0.0 (a59de37e9 2015-05-13) (built 2015-05-14)
dm-mbp:rustfmt minsler$ cargo -V
cargo 0.2.0-nightly (efb482d 2015-04-30) (built 2015-04-29)

dm-mbp:rustfmt minsler$ cargo build
   Compiling strings v0.0.1 (https://github.com/nrc/strings.rs.git#551331d0)
/Users/minsler/.cargo/git/checkouts/strings.rs-3047d54c6ac12a97/master/src/rope.rs:20:1: 20:28 error: can't find crate for `rustc_unicode`
/Users/minsler/.cargo/git/checkouts/strings.rs-3047d54c6ac12a97/master/src/rope.rs:20 extern crate rustc_unicode;
                                                                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~
error: aborting due to previous error
Could not compile `strings`.
</pre>

Thank you for help in advance.

**Comment by nrc** [comment]
I think it is because you are building with the release version of Rust. rustfmt requires a recent nightly. You can install nightly Rust with

```
curl -sSf https://static.rust-lang.org/rustup.sh | sh -s -- --channel=nightly
```

If you want to also run release builds, you should look into multirust.

**Comment by minsler** [comment]
Thanks,  it was built with a recent nightly version.
