### ISSUE TITLE
proper error handling

### ISSUE THREAD

**Issue by nrc** [nrc/rustfmt#9]
We're a bit too println-happy at the moment

**Comment by marcusklaas** [comment]
Where would we store the errors? In `ChangeSet`? And if so, would we store them along with the results in `file_map` or add a new hash map for the errors. Also, should we store any thing other than file name and error message such as line numbers?

**Comment by nrc** [comment]
I would create a new data structure to keep track of errors, rather than using ChangeSet. To start with, just keeping an ordered list of filename, file line (or a Span, if that is easy), and message is the best idea. Later we might want more sophisticated tracking.

**Comment by marcusklaas** [comment]
Can we close this? The primary public function, `rustfmt::format`, does not write to stdout.

**Comment by nrc** [comment]
Yeah, I think we're good
